name: Publish Release

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore: 
      - .github/workflows/*

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      python_ver: 3.11

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'plugin.json'
          prop_path: 'Version'

      - name: Future dist name of the plugin
        id: plugin_dist_filename
        run: |
          DIST_FILENAME=Flow.Launcher.Plugin.Totp_v${{steps.version.outputs.prop}}.zip
          echo "Dist is: $DIST_FILENAME"
          echo "DIST_FILENAME=$DIST_FILENAME" >> $GITHUB_ENV

      - run: echo ${{steps.version.outputs.prop}} 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt -t ./lib
          zip -r ${{ env.DIST_FILENAME }} . -x '*.git*' -x 'assets/*'

      - name: Publish
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.DIST_FILENAME }}
          tag_name: "v${{steps.version.outputs.prop}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}